//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressState
    {
        public AddressState()
        {
            this.AddressCity = new HashSet<AddressCity>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        public virtual ICollection<AddressCity> AddressCity { get; set; }
    }
}
