//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarnameHaftegi
    {
        public BarnameHaftegi()
        {
            this.HozoorGhiab = new HashSet<HozoorGhiab>();
            this.NomreKelasi = new HashSet<NomreKelasi>();
            this.TaklifKelasiJami = new HashSet<TaklifKelasiJami>();
            this.TaklifKelasi = new HashSet<TaklifKelasi>();
            this.TashvighTanbihKelasi = new HashSet<TashvighTanbihKelasi>();
        }
    
        public int ID { get; set; }
        public Nullable<int> F_MoallemDoroosID { get; set; }
        public Nullable<int> F_KelasID { get; set; }
        public Nullable<int> Zang { get; set; }
        public Nullable<int> Ruz { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> Fovgholade { get; set; }
        public string F_ParrentID { get; set; }
    
        public virtual Kelas Kelas { get; set; }
        public virtual Mapping_Moallem_Doroos Mapping_Moallem_Doroos { get; set; }
        public virtual ICollection<HozoorGhiab> HozoorGhiab { get; set; }
        public virtual ICollection<NomreKelasi> NomreKelasi { get; set; }
        public virtual ICollection<TaklifKelasiJami> TaklifKelasiJami { get; set; }
        public virtual ICollection<TaklifKelasi> TaklifKelasi { get; set; }
        public virtual ICollection<TashvighTanbihKelasi> TashvighTanbihKelasi { get; set; }
    }
}
