//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarnameEmtehani
    {
        public BarnameEmtehani()
        {
            this.NomreEmtehani = new HashSet<NomreEmtehani>();
        }
    
        public int ID { get; set; }
        public Nullable<int> F_MoallemDoroosID { get; set; }
        public Nullable<int> F_KelasID { get; set; }
        public Nullable<System.DateTime> TarikhKamel { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string F_ParrentID { get; set; }
    
        public virtual Kelas Kelas { get; set; }
        public virtual Mapping_Moallem_Doroos Mapping_Moallem_Doroos { get; set; }
        public virtual ICollection<NomreEmtehani> NomreEmtehani { get; set; }
    }
}
