//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaneshAmuz
    {
        public DaneshAmuz()
        {
            this.HozoorGhiabKelasi = new HashSet<HozoorGhiabKelasi>();
            this.NomreEmtehani = new HashSet<NomreEmtehani>();
            this.NomreKelasi = new HashSet<NomreKelasi>();
            this.TaklifKelasi = new HashSet<TaklifKelasi>();
            this.TashvighTanbihKelasi = new HashSet<TashvighTanbihKelasi>();
        }
    
        public int ID { get; set; }
        public Nullable<int> F_KelasID { get; set; }
        public Nullable<int> F_OvliaID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CodeMelli { get; set; }
        public string ShomareShenasname { get; set; }
        public string TarikhTavallod { get; set; }
        public string MahalleSodoor { get; set; }
        public Nullable<bool> Jensiat { get; set; }
        public string NesbateVali { get; set; }
        public string Tovzihat { get; set; }
        public string F_ParrentID { get; set; }
    
        public virtual Kelas Kelas { get; set; }
        public virtual Ovlia Ovlia { get; set; }
        public virtual ICollection<HozoorGhiabKelasi> HozoorGhiabKelasi { get; set; }
        public virtual ICollection<NomreEmtehani> NomreEmtehani { get; set; }
        public virtual ICollection<NomreKelasi> NomreKelasi { get; set; }
        public virtual ICollection<TaklifKelasi> TaklifKelasi { get; set; }
        public virtual ICollection<TashvighTanbihKelasi> TashvighTanbihKelasi { get; set; }
    }
}
