//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SCEntities : DbContext
    {
        public SCEntities()
            : base("name=SCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressCity> AddressCity { get; set; }
        public virtual DbSet<AddressState> AddressState { get; set; }
        public virtual DbSet<BarnameEmtehani> BarnameEmtehani { get; set; }
        public virtual DbSet<BarnameHaftegi> BarnameHaftegi { get; set; }
        public virtual DbSet<Check> Check { get; set; }
        public virtual DbSet<DaneshAmuz> DaneshAmuz { get; set; }
        public virtual DbSet<Doroos> Doroos { get; set; }
        public virtual DbSet<Farakhanha> Farakhanha { get; set; }
        public virtual DbSet<Hazine> Hazine { get; set; }
        public virtual DbSet<HozoorGhiab> HozoorGhiab { get; set; }
        public virtual DbSet<HozoorGhiabKelasi> HozoorGhiabKelasi { get; set; }
        public virtual DbSet<Karmandaan> Karmandaan { get; set; }
        public virtual DbSet<Kelas> Kelas { get; set; }
        public virtual DbSet<Madaares> Madaares { get; set; }
        public virtual DbSet<Maghaate> Maghaate { get; set; }
        public virtual DbSet<Mapping_Farakhanha_Kelas> Mapping_Farakhanha_Kelas { get; set; }
        public virtual DbSet<Mapping_Moallem_Doroos> Mapping_Moallem_Doroos { get; set; }
        public virtual DbSet<Moallem> Moallem { get; set; }
        public virtual DbSet<Nemayandegi> Nemayandegi { get; set; }
        public virtual DbSet<NomreEmtehani> NomreEmtehani { get; set; }
        public virtual DbSet<NomreKelasi> NomreKelasi { get; set; }
        public virtual DbSet<Ovlia> Ovlia { get; set; }
        public virtual DbSet<Paaye> Paaye { get; set; }
        public virtual DbSet<Pardakht> Pardakht { get; set; }
        public virtual DbSet<Payamha> Payamha { get; set; }
        public virtual DbSet<SaleTahsili> SaleTahsili { get; set; }
        public virtual DbSet<SchoolLog> SchoolLog { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<TaklifKelasi> TaklifKelasi { get; set; }
        public virtual DbSet<TaklifKelasiJami> TaklifKelasiJami { get; set; }
        public virtual DbSet<TashvighTanbihKelasi> TashvighTanbihKelasi { get; set; }
        public virtual DbSet<UserInformation> UserInformation { get; set; }
    }
}
