//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doroos
    {
        public Doroos()
        {
            this.Mapping_Moallem_Doroos = new HashSet<Mapping_Moallem_Doroos>();
        }
    
        public int ID { get; set; }
        public Nullable<int> F_PayeID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string NaameDars { get; set; }
        public Nullable<int> ZaribeDars { get; set; }
        public Nullable<bool> Sabet { get; set; }
        public Nullable<int> F_MadaaresID { get; set; }
        public string F_ParrentID { get; set; }
    
        public virtual Madaares Madaares { get; set; }
        public virtual Paaye Paaye { get; set; }
        public virtual ICollection<Mapping_Moallem_Doroos> Mapping_Moallem_Doroos { get; set; }
    }
}
