//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farakhanha
    {
        public Farakhanha()
        {
            this.Mapping_Farakhanha_Kelas = new HashSet<Mapping_Farakhanha_Kelas>();
        }
    
        public int ID { get; set; }
        public Nullable<int> F_KarmandanID { get; set; }
        public string Movzoo { get; set; }
        public string Matn { get; set; }
        public Nullable<System.DateTime> TarikheFarakhan { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string F_ParrentID { get; set; }
    
        public virtual Karmandaan Karmandaan { get; set; }
        public virtual ICollection<Mapping_Farakhanha_Kelas> Mapping_Farakhanha_Kelas { get; set; }
    }
}
