//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HozoorGhiab
    {
        public HozoorGhiab()
        {
            this.HozoorGhiabKelasi = new HashSet<HozoorGhiabKelasi>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Tarikh { get; set; }
        public Nullable<int> Hafte { get; set; }
        public Nullable<bool> isChecked { get; set; }
        public Nullable<int> F_BarnameHaftegi { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string F_ParrentID { get; set; }
    
        public virtual BarnameHaftegi BarnameHaftegi { get; set; }
        public virtual ICollection<HozoorGhiabKelasi> HozoorGhiabKelasi { get; set; }
    }
}
