//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kelas
    {
        public Kelas()
        {
            this.BarnameEmtehani = new HashSet<BarnameEmtehani>();
            this.BarnameHaftegi = new HashSet<BarnameHaftegi>();
            this.DaneshAmuz = new HashSet<DaneshAmuz>();
            this.Mapping_Farakhanha_Kelas = new HashSet<Mapping_Farakhanha_Kelas>();
            this.TaklifKelasiJami = new HashSet<TaklifKelasiJami>();
        }
    
        public int ID { get; set; }
        public Nullable<int> F_MadaresID { get; set; }
        public Nullable<int> F_PayeID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string NaameKelas { get; set; }
        public Nullable<int> MaxZang { get; set; }
        public string F_ParrentID { get; set; }
    
        public virtual ICollection<BarnameEmtehani> BarnameEmtehani { get; set; }
        public virtual ICollection<BarnameHaftegi> BarnameHaftegi { get; set; }
        public virtual ICollection<DaneshAmuz> DaneshAmuz { get; set; }
        public virtual Madaares Madaares { get; set; }
        public virtual Paaye Paaye { get; set; }
        public virtual ICollection<Mapping_Farakhanha_Kelas> Mapping_Farakhanha_Kelas { get; set; }
        public virtual ICollection<TaklifKelasiJami> TaklifKelasiJami { get; set; }
    }
}
