//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maghaate
    {
        public Maghaate()
        {
            this.Madaares = new HashSet<Madaares>();
            this.Paaye = new HashSet<Paaye>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string NaameMaghta { get; set; }
    
        public virtual ICollection<Madaares> Madaares { get; set; }
        public virtual ICollection<Paaye> Paaye { get; set; }
    }
}
