//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapping_Moallem_Doroos
    {
        public Mapping_Moallem_Doroos()
        {
            this.BarnameEmtehani = new HashSet<BarnameEmtehani>();
            this.BarnameHaftegi = new HashSet<BarnameHaftegi>();
        }
    
        public int ID { get; set; }
        public Nullable<int> F_MoallemID { get; set; }
        public Nullable<int> F_DoroosID { get; set; }
        public string F_ParrentID { get; set; }
    
        public virtual ICollection<BarnameEmtehani> BarnameEmtehani { get; set; }
        public virtual ICollection<BarnameHaftegi> BarnameHaftegi { get; set; }
        public virtual Doroos Doroos { get; set; }
        public virtual Moallem Moallem { get; set; }
    }
}
