//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moallem
    {
        public Moallem()
        {
            this.Mapping_Moallem_Doroos = new HashSet<Mapping_Moallem_Doroos>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> Jensiat { get; set; }
        public string NamePedar { get; set; }
        public string ShomareShenasname { get; set; }
        public string TarikhTavallod { get; set; }
        public string MahaleSodoor { get; set; }
        public string Address { get; set; }
        public string F_UserInformation { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> F_MadaaresID { get; set; }
        public string F_ParrentID { get; set; }
    
        public virtual Madaares Madaares { get; set; }
        public virtual ICollection<Mapping_Moallem_Doroos> Mapping_Moallem_Doroos { get; set; }
        public virtual UserInformation UserInformation { get; set; }
    }
}
