//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nemayandegi
    {
        public Nemayandegi()
        {
            this.Madaares = new HashSet<Madaares>();
        }
    
        public int ID { get; set; }
        public string F_UserID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Name { get; set; }
        public Nullable<int> F_CityId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string Tell { get; set; }
        public string Email { get; set; }
        public string AddressDetail { get; set; }
    
        public virtual AddressCity AddressCity { get; set; }
        public virtual ICollection<Madaares> Madaares { get; set; }
    }
}
