//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ovlia
    {
        public Ovlia()
        {
            this.DaneshAmuz = new HashSet<DaneshAmuz>();
            this.Hazine = new HashSet<Hazine>();
        }
    
        public int ID { get; set; }
        public string F_UserInformationID { get; set; }
        public string Mobile { get; set; }
        public string F_ParrentID { get; set; }
    
        public virtual ICollection<DaneshAmuz> DaneshAmuz { get; set; }
        public virtual ICollection<Hazine> Hazine { get; set; }
        public virtual UserInformation UserInformation { get; set; }
    }
}
