//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payamha
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CreatedDateOnUTC { get; set; }
        public string F_FromID { get; set; }
        public string F_ToID { get; set; }
        public string Text { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual UserInformation UserInformation { get; set; }
        public virtual UserInformation UserInformation1 { get; set; }
    }
}
