//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleTahsili
    {
        public SaleTahsili()
        {
            this.Madaares = new HashSet<Madaares>();
        }
    
        public int ID { get; set; }
        public string Sal { get; set; }
    
        public virtual ICollection<Madaares> Madaares { get; set; }
    }
}
