//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolLog
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public Nullable<int> TableRecordID { get; set; }
        public string TableFields { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> DateOnUTC { get; set; }
        public Nullable<int> OperationID { get; set; }
    }
}
