//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolService.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public UserInformation()
        {
            this.Karmandaan = new HashSet<Karmandaan>();
            this.Moallem = new HashSet<Moallem>();
            this.Ovlia = new HashSet<Ovlia>();
            this.Payamha = new HashSet<Payamha>();
            this.Payamha1 = new HashSet<Payamha>();
        }
    
        public string ID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> F_MadaaresID { get; set; }
        public string CodeMelli { get; set; }
        public string AndroidID { get; set; }
    
        public virtual ICollection<Karmandaan> Karmandaan { get; set; }
        public virtual Madaares Madaares { get; set; }
        public virtual ICollection<Moallem> Moallem { get; set; }
        public virtual ICollection<Ovlia> Ovlia { get; set; }
        public virtual ICollection<Payamha> Payamha { get; set; }
        public virtual ICollection<Payamha> Payamha1 { get; set; }
    }
}
